### ISSUE TITLE
Track1: baseline results

### ISSUE THREAD

**Issue by striver314** [blcuicall/CCL2022-CLTC#11]
根据评价标准，赛道一包括句级（Sentence Level）和字级（Character Level）两种级别的Dection和Correction结果，请问目前baseline给出的结果属于哪类？是否会补充另一个级别的评价结果？最终该赛道的结果排名以什么指标为准呢？

**Comment by YingyWang** [comment]
现在给的是sentence level的结果，随后会补充character level的。排行榜暂计划以sentence level f1为标准排名。

**Comment by YingyWang** [comment]
> 现在给的是sentence level的结果，随后会补充character level的。排行榜暂计划以sentence level f1为标准排名。



> 根据评价标准，赛道一包括句级（Sentence Level）和字级（Character Level）两种级别的Dection和Correction结果，请问目前baseline给出的结果属于哪类？是否会补充另一个级别的评价结果？最终该赛道的结果排名以什么指标为准呢？

**Comment by striver314** [comment]
了解，谢谢。
