### ISSUE TITLE
关于track1数据 ：音近、形近、形音兼近三种。

### ISSUE THREAD

**Issue by xk503775229** [blcuicall/CCL2022-CLTC#12]
官方通知的：音近、形近、形音兼近三种。
想了解拼写是否只是这个范畴的，最终测试集错误样式是否与dev相似？

**Comment by YingyWang** [comment]
你好，测试集错误类型仍是仅音近、形近、形音兼近三种。
开发集的标注过程中有极少数的人工失误，总体不影响评测。
谢谢反馈~
