### ISSUE TITLE
请问如何报名？

### ISSUE THREAD

**Issue by Dicer-Zz** [blcuicall/CCL2022-CLTC#2]
似乎没有看到报名链接和方式。

**Comment by YingyWang** [comment]
> 

暂未开始报名，敬请期待，感谢关注！

**Comment by Young1993** [comment]
请问何时发布 报名链接和方式，谢谢！

**Comment by striver314** [comment]
请问现在可以开始报名了吗？

**Comment by egnq** [comment]
请问报名方式出来了吗

**Comment by styxjedi** [comment]
大家好，请大家关注更新后的报名时间。

**Comment by styxjedi** [comment]
大家好，请关注更新后的[报名时间](https://github.com/blcuicall/CCL2022-CLTC#4-%E8%AF%84%E6%B5%8B%E8%B5%9B%E7%A8%8B)。

报名时间： 6 月 1 日 ~ 7 月 20 日

报名入口后续会在智源指数（赛道一、二、三、五）和天池平台（赛道四）上开放。

**Comment by xk503775229** [comment]
报名时间又推迟了吗？今天6.1号

**Comment by styxjedi** [comment]
你好，是的，报名系统将在6月5日开放。

> 报名时间又推迟了吗？今天6.1号

**Comment by henryhuanghenry** [comment]
您好，请问报名的话，是否关注这个网站：http://cuge.baai.ac.cn/#/？

**Comment by styxjedi** [comment]
> 您好，请问报名的话，是否关注这个网站：[http://cuge.baai.ac.cn/#/？](http://cuge.baai.ac.cn/#/%EF%BC%9F)

报名入口会在 CUGE 平台上开放，同时也会在本 github 仓库更新消息，请关注下方链接：

https://github.com/blcuicall/CCL2022-CLTC/blob/main/README.md#最新消息

**Comment by YingyWang** [comment]
各位好，报名方式已更新，请查阅本仓库最新消息。
