### ISSUE TITLE
关于评测数据的来源

### ISSUE THREAD

**Issue by wang136906578** [blcuicall/CCL2022-CLTC#5]
组织者您好！我想请教一下赛道一：中文拼写检查的评测数据来源。介绍中提及这一任务使用YACLC-CSC 作为评测数据。我读了arxiv上的论文，文中说YACLC的数据收集自语言学习网站Lang-8。不过文中似乎并未提及本次比赛中使用的YACLC-CSC、YACLC-Minimal、YACLC-Fluency等名称中带后缀的数据集来源。请问这些数据集也是跟YACLC一样使用的收集自Lang-8的数据吗？

**Comment by YingyWang** [comment]
是的 ，YACLC-CSC、YACLC-Minimal、YACLC-Fluency本就选取自YACLC数据库。
