### ISSUE TITLE
报名信息没了？

### ISSUE THREAD

**Issue by kekheh2019** [blcuicall/CCL2022-CLTC#9]
之前的报名信息和队伍信息都没有了，这是做了啥操作呢？

**Comment by styxjedi** [comment]
十分抱歉，近日报名系统出现故障，需要您重新注册并报名参赛。
给您带来不便之处，还望谅解！

**Comment by styxjedi** [comment]
实在抱歉，由于平台故障，部分报名数据丢失，需要您重新注册并报名参赛。

带来不便之处，望您谅解！

详情请看：https://github.com/blcuicall/CCL2022-CLTC/blob/main/docs/06-14-cuge-re-register.md

**Comment by kekheh2019** [comment]
好的，谢谢，已经重新报名



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Cunliang ***@***.***> |
| 日期 | 2022年06月14日 10:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [blcuicall/CCL2022-CLTC] 报名信息没了？ (Issue #9) |

实在抱歉，由于平台故障，部分报名数据丢失，需要您重新注册并报名参赛。

带来不便之处，望您谅解！

详情请看：https://github.com/blcuicall/CCL2022-CLTC/blob/main/docs/06-14-cuge-re-register.md
